name = "Gregsfactory 3"
author = "Annwan, LunaFreyja, PhoenixAscencio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b23d0c88fd02959d0bfca2db6b09e2e3833c31a05866e8bccb4e9bf866c68fb"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
