name = "Gregsfactory 3"
author = "Annwan, LunaFreyja, PhoenixAscencio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2510aebdf23addcfa7b1b8bfa29c9660297ab048d912d90cc81475b69db54e0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
