name = "Gregsfactory 3"
author = "Annwan, LunaFreyja, PhoenixAscencio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08006edb2cb5372f5c362b73e69ad389de7a409b49b67cd2f550ef567ac4805d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
