name = "Gregsfactory 3"
author = "Annwan, LunaFreyja, PhoenixAscencio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b46dbb6d66ce133908bede92ad81e0d099d35592028e5cdfd8d448cac24c2924"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
