name = "Gregsfactory 3"
author = "Annwan, LunaFreyja, PhoenixAscencio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df46874534e510f86e19eaa5cd586d256b8f7a3dc1f9eee2b9e6403f73185fd2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
