name = "Gregsfactory 3"
author = "Annwan, LunaFreyja, PhoenixAscencio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61de7e2971967db9ce4fa92719f776ecddd1002e10f3bb8bbc4a5ec0bc620172"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
